"""LuaLaTeX PDF compilation with error handling."""

import shutil
import subprocess
from pathlib import Path


class CompilationError(Exception):
    """Raised when lualatex compilation fails."""

    def __init__(self, message: str, log_content: str = ""):
        super().__init__(message)
        self.log_content = log_content


def compile_to_pdf(
    tex_path: Path,
    lualatex_cmd: str = "lualatex",
) -> Path:
    """Compile a .tex file to PDF using lualatex."""
    if not tex_path.exists():
        raise FileNotFoundError(f"TeX file not found: {tex_path}")

    if not shutil.which(lualatex_cmd):
        raise CompilationError(
            f"'{lualatex_cmd}' not found. Install a LaTeX distribution "
            "(MiKTeX or TeX Live) with LuaLaTeX support."
        )

    output_dir = tex_path.parent

    # Run lualatex twice (for cross-references)
    for run in range(2):
        result = subprocess.run(
            [
                lualatex_cmd,
                "-interaction=nonstopmode",
                f"-output-directory={output_dir}",
                str(tex_path),
            ],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(output_dir),
        )

        if result.returncode != 0:
            log_path = tex_path.with_suffix(".log")
            log_content = ""
            if log_path.exists():
                log_content = log_path.read_text(encoding="utf-8", errors="replace")
                errors = _extract_errors(log_content)
            else:
                errors = result.stderr or result.stdout

            raise CompilationError(
                f"lualatex compilation failed (run {run + 1}):\n{errors}",
                log_content=log_content,
            )

    pdf_path = tex_path.with_suffix(".pdf")
    if not pdf_path.exists():
        raise CompilationError("Compilation succeeded but no PDF was produced.")

    _cleanup_aux(tex_path)
    return pdf_path


def _extract_errors(log_content: str) -> str:
    """Extract meaningful error lines from a lualatex log."""
    error_lines: list[str] = []
    for line in log_content.split("\n"):
        if line.startswith("!") or "Error" in line or "Undefined" in line:
            error_lines.append(line)
    if error_lines:
        return "\n".join(error_lines[:20])
    return "Unknown error (check .log file)"


def _cleanup_aux(tex_path: Path) -> None:
    """Remove auxiliary files generated by lualatex."""
    for ext in [".aux", ".log", ".out", ".synctex.gz"]:
        aux = tex_path.with_suffix(ext)
        if aux.exists():
            aux.unlink()
